Repository cloudfoundry/docs-cfcr, pull requests merged in 2018-03, with the labels that each got.

#44 key name is consistent
  docs/installing/gcp/deploying-bosh-gcp.md
Labels: unscheduled

#43 consistent path to gcp key
  docs/managing/deleting.md
Labels: unscheduled

#42 Provide state to terraform when destroying
  docs/managing/deleting.md
Labels: scheduled

#41 Routing has to be done prior to deploying bosh
  docs/installing/gcp/index.md
Labels: scheduled

#46 The user is instructed to set private_key_filename for this path
  docs/installing/aws/deploying-bosh-aws.md
  docs/installing/aws/routing-aws.md
  docs/installing/deploying-cfcr.md
Labels: in progress

#47 Add release notes for v0.15
  docs/overview/release-notes.md
Labels: unscheduled

#48 Instruct to deploy_bosh to update cc:elb
  docs/installing/aws/routing-aws.md
Labels: in progress
