Repository cloudfoundry/docs-cfcr, pull requests merged in 2018-07, with the labels that each got.

#50 Modify stemcell version
  docs/overview/release-notes.md
Labels: scheduled

#51 Add deprecation warning
  docs/index.md
Labels: scheduled

#52 Deprecate route-sync
  docs/installing/deploying-cfcr.md
Labels: unscheduled

#53 add dependencies to set_kubeconfig
  docs/installing/deploying-cfcr.md
Labels: in progress
